/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://rdlliubhibacndbs3i3wz5tajm.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ron2rrc2bbaj5hhyiaszulp3li",
    "aws_cloud_logic_custom": [
        {
            "name": "laundryapi",
            "endpoint": "https://3trhkuspw9.execute-api.us-west-2.amazonaws.com/staging",
            "region": "us-west-2"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "laundrydb-staging",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
